spring.docker.compose.enabled=false

spring.datasource.url=${DB_URL}
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}

spring.jpa.show-sql=true

discord.bot.token=${DISCORD_BOT_TOKEN}

app.cors.allowed-origins=http://localhost:3000

jwt.secret=${JWT_SECRET}