"use client";

import { useState, useEffect, useMemo } from "react";
import { useSession } from "next-auth/react";
import {
  Search,
  Plus,
  Shield,
  User,
  UserCog,
  CheckCircle2,
  XCircle,
  X,
  Loader2,
  AlertTriangle,
  Save,
  Trash2,
  Edit,
  Crown,
} from "lucide-react";
import api from "@/lib/axios";
import { toast } from "sonner";

interface DiscordUser {
  idUser: number;
  discordId: string;
  username: string;
  globalRole: "ADMIN" | "STAFF" | "USER";
  status: "ACTIVE" | "INACTIVE" | "ELIMINATED" | "NOT_CONTESTANT" | "DID_NOT_SUBMIT";
  host?: boolean;
}

// Omit idUser for create payload since it's generated by the backend
type FormDataPayload = Omit<DiscordUser, "idUser">;

const INITIAL_FORM_STATE: FormDataPayload = {
  discordId: "",
  username: "",
  globalRole: "USER",
  status: "NOT_CONTESTANT",
};

const GLOBAL_ROLES = ["ADMIN", "STAFF", "USER"];
const STATUS_OPTIONS = ["ACTIVE", "INACTIVE", "ELIMINATED", "NOT_CONTESTANT", "DID_NOT_SUBMIT"];

export default function UsersPage() {
  const { data: session, status: authStatus } = useSession();

  // Cast the role safely from the session
  const userRole = (session?.user as any)?.role || "USER";
  const isAdmin = userRole === "ADMIN";

  const currentUserId = session?.user?.discordId;

  // State management
  const [users, setUsers] = useState<DiscordUser[]>([]);
  const [isLoading, setIsLoading] = useState(true);

  // Filter states
  const [searchTerm, setSearchTerm] = useState("");
  const [selectedRoles, setSelectedRoles] = useState<string[]>(GLOBAL_ROLES);
  const [selectedStatuses, setSelectedStatuses] = useState<string[]>(
    STATUS_OPTIONS.filter((s) => s !== "INACTIVE"),
  );

  // Modal and form state
  const [isModalOpen, setIsModalOpen] = useState(false);
  const [editingUserId, setEditingUserId] = useState<number | null>(null);
  const [formData, setFormData] = useState<FormDataPayload>(INITIAL_FORM_STATE);
  const [isSubmitting, setIsSubmitting] = useState(false);
  const [userToDelete, setUserToDelete] = useState<DiscordUser | null>(null);

  // Fetch users on component mount
  useEffect(() => {
    if (authStatus === "authenticated") {
      fetchUsers();
    }
  }, [authStatus]);

  const fetchUsers = async () => {
    const token = session?.accessToken;

    if (!token) {
      console.error("No access token found in session. User might not be authenticated.");
      setIsLoading(false);
      return;
    }

    try {
      setIsLoading(true);
      const res = await api.get(`/users`);

      // Sort users by global role (ADMIN > STAFF > USER) and then alphabetically by username ascending
      res.data.sort((a: DiscordUser, b: DiscordUser) => {
        const rolePriority = { ADMIN: 3, STAFF: 2, USER: 1 };
        if (rolePriority[a.globalRole] !== rolePriority[b.globalRole]) {
          return rolePriority[b.globalRole] - rolePriority[a.globalRole];
        }
        return a.username.localeCompare(b.username, undefined, { sensitivity: "base" });
      });
      setUsers(res.data);
    } catch (error: any) {
      // Error handled by interceptor
    } finally {
      setIsLoading(false);
    }
  };

  const handleOpenCreate = () => {
    setEditingUserId(null);
    setFormData(INITIAL_FORM_STATE);
    setIsModalOpen(true);
  };

  const handleOpenEdit = (user: DiscordUser) => {
    setEditingUserId(user.idUser);
    setFormData({
      discordId: user.discordId,
      username: user.username,
      globalRole: user.globalRole,
      status: user.status,
      host: user.host || false,
    });
    setIsModalOpen(true);
  };

  const handleSubmit = async (e: React.SubmitEvent<HTMLFormElement>) => {
    e.preventDefault();

    const token = session?.accessToken;

    if (!token) {
      console.error("No access token found in session. User might not be authenticated.");
      return;
    }

    try {
      setIsSubmitting(true);

      if (editingUserId) {
        // Update existing user
        const updatedData: DiscordUser = {
          idUser: editingUserId,
          ...formData,
        };

        const res = await api.put(`/users/${editingUserId}`, updatedData);

        const updatedUser = res.data;

        // Update the user in the local state
        setUsers((prevUsers) =>
          prevUsers.map((user) => (user.idUser === updatedUser.idUser ? updatedUser : user)),
        );

        toast.success("User updated successfully.", {
          description: `${updatedUser.username} has been updated.`,
          closeButton: true,
        });
      } else {
        // Create new user
        const createPayload: FormDataPayload = {
          discordId: formData.discordId,
          username: formData.username,
          globalRole: formData.globalRole,
          status: formData.status,
          host: formData.host,
        };

        const res = await api.post(`/users`, createPayload);

        const newUser = res.data;

        // Add the new user to the local state
        setUsers((prevUsers) => [...prevUsers, newUser]);

        toast.success("User created successfully.", {
          description: `${newUser.username} has been added to the system.`,
          closeButton: true,
        });
      }

      // Close modal and reset form
      setIsModalOpen(false);
      setFormData(INITIAL_FORM_STATE);
    } catch (error: any) {
      // Error handled by interceptor
    } finally {
      setIsSubmitting(false);
    }
  };

  const handleDeleteConfirm = async () => {
    if (!userToDelete) return;

    try {
      setIsSubmitting(true);

      await api.delete(`/users/${userToDelete.idUser}`);

      // Remove the deleted user from local state
      setUsers((prevUsers) => prevUsers.filter((user) => user.idUser !== userToDelete.idUser));

      toast.success("User deleted successfully.", {
        description: `${userToDelete.username} has been removed from the system.`,
        closeButton: true,
      });

      setUserToDelete(null);
    } catch (error: any) {
      // Error handled by interceptor
    } finally {
      setIsSubmitting(false);
    }
  };

  // Filter logic
  const filteredUsers = useMemo(() => {
    return users.filter((user) => {
      const matchesSearch =
        user.username.toLowerCase().includes(searchTerm.toLowerCase()) ||
        user.discordId.includes(searchTerm);

      const matchesRole = selectedRoles.includes(user.globalRole);
      const matchesStatus = selectedStatuses.includes(user.status);

      return matchesSearch && matchesRole && matchesStatus;
    });
  }, [users, searchTerm, selectedRoles, selectedStatuses]);

  return (
    <div className="space-y-6 relative">
      {/* Header Section */}
      <div className="flex flex-col sm:flex-row sm:items-center justify-between gap-4">
        <div>
          <h1 className="text-2xl font-bold text-white">User Management</h1>
          <p className="text-[#80848E] text-sm mt-1">View and manage users for the competition.</p>
        </div>

        {isAdmin && (
          <button
            onClick={handleOpenCreate}
            className="bg-[#5865F2] hover:bg-[#4752C4] text-white px-4 py-2 rounded-md font-medium flex items-center justify-center transition-colors shadow-lg"
          >
            <Plus className="w-4 h-4 mr-2" />
            Add User
          </button>
        )}
      </div>

      {/* Search and Filters Toolbar */}
      <div className="bg-[#2B2D31] p-4 rounded-t-lg border border-[#1E1F22] space-y-4">
        <div className="relative w-full max-w-md">
          <Search className="absolute left-3 top-1/2 -translate-y-1/2 w-4 h-4 text-[#80848E]" />
          <input
            type="text"
            placeholder="Search by username or Discord ID..."
            value={searchTerm}
            onChange={(e) => setSearchTerm(e.target.value)}
            className="w-full bg-[#1E1F22] border-none text-[#DBDEE1] text-sm rounded-md pl-10 pr-4 py-2 focus:ring-1 focus:ring-[#5865F2] outline-none placeholder:text-[#80848E]"
          />
        </div>

        <div className="flex flex-wrap items-center gap-6 pt-2 border-t border-[#35373C]">
          {/* Global Roles Filter */}
          <div className="space-y-2">
            <label className="text-[10px] font-bold text-[#80848E] uppercase tracking-wider">
              Global Roles
            </label>
            <div className="flex gap-2">
              {GLOBAL_ROLES.map((role) => (
                <button
                  key={role}
                  onClick={() =>
                    setSelectedRoles((prev) =>
                      prev.includes(role) ? prev.filter((r) => r !== role) : [...prev, role],
                    )
                  }
                  className={`px-3 py-1 rounded text-xs font-semibold transition-all border ${
                    selectedRoles.includes(role)
                      ? "bg-[#5865F2] border-[#7883f8] text-white"
                      : "bg-[#1E1F22] border-[#35373C] text-[#80848E] hover:border-[#4E5058]"
                  }`}
                >
                  {role}
                </button>
              ))}
            </div>
          </div>

          {/* Status Filter */}
          <div className="space-y-2">
            <label className="text-[10px] font-bold text-[#80848E] uppercase tracking-wider">
              User Status
            </label>
            <div className="flex flex-wrap gap-2">
              {STATUS_OPTIONS.map((status) => (
                <button
                  key={status}
                  onClick={() =>
                    setSelectedStatuses((prev) =>
                      prev.includes(status) ? prev.filter((s) => s !== status) : [...prev, status],
                    )
                  }
                  className={`px-3 py-1 rounded text-xs font-semibold transition-all border ${
                    selectedStatuses.includes(status)
                      ? "bg-emerald-600 border-emerald-500 text-white"
                      : "bg-[#1E1F22] border-[#35373C] text-[#80848E] hover:border-[#4E5058]"
                  }`}
                >
                  {status.replace(/_/g, " ")}
                </button>
              ))}
            </div>
          </div>

          {/* Reset button */}
          {(selectedRoles.length !== GLOBAL_ROLES.length ||
            selectedStatuses.length !== STATUS_OPTIONS.length - 1) && (
            <button
              onClick={() => {
                setSelectedRoles(GLOBAL_ROLES);
                setSelectedStatuses(STATUS_OPTIONS.filter((s) => s !== "INACTIVE"));
              }}
              className="text-[10px] text-[#5865F2] hover:underline mt-6 font-bold uppercase"
            >
              Reset Filters
            </button>
          )}
        </div>
      </div>

      {/* Data Table */}
      <div className="bg-[#2B2D31] rounded-b-lg border border-t-0 border-[#1E1F22] overflow-x-auto min-h-75">
        {isLoading ? (
          <div className="flex flex-col items-center justify-center h-64 text-[#80848E]">
            <Loader2 className="w-8 h-8 animate-spin text-[#5865F2] mb-4" />
            <p>Loading users...</p>
          </div>
        ) : (
          <table className="w-full text-left text-sm text-[#DBDEE1]">
            <thead className="text-xs text-[#80848E] uppercase bg-[#1E1F22]/50 border-b border-[#1E1F22]">
              <tr>
                <th className="px-6 py-4 font-semibold">User</th>
                <th className="px-6 py-4 font-semibold">Discord ID</th>
                <th className="px-6 py-4 font-semibold">Global Role</th>
                <th className="px-6 py-4 font-semibold">Status</th>
                {isAdmin && <th className="px-6 py-4 font-semibold text-right">Actions</th>}
              </tr>
            </thead>
            <tbody>
              {filteredUsers.length > 0 ? (
                filteredUsers.map((user) => (
                  <tr
                    key={user.idUser}
                    className="border-b border-[#1E1F22] hover:bg-[#35373C]/50 transition-colors"
                  >
                    {/* Username */}
                    <td className="px-6 py-4 font-medium text-white flex items-center gap-3">
                      <div className="w-8 h-8 rounded-full bg-[#5865F2]/20 flex items-center justify-center text-[#5865F2]">
                        {user.username.charAt(0).toUpperCase()}
                      </div>
                      {user.username}
                    </td>

                    {/* Discord ID */}
                    <td className="px-6 py-4 text-[#80848E] font-mono text-xs">{user.discordId}</td>

                    {/* Global Role */}
                    <td className="px-6 py-4">
                      <span
                        className={`inline-flex items-center gap-1.5 px-2.5 py-1 rounded-full text-xs font-medium border ${
                          user.host
                            ? "bg-amber-500/10 text-amber-400 border-amber-500/30 shadow-[0_0_10px_rgba(251,191,36,0.2)]"
                            : user.globalRole === "ADMIN"
                              ? "bg-red-500/10 text-red-400 border-red-500/20"
                              : user.globalRole === "STAFF"
                                ? "bg-blue-500/10 text-blue-400 border-blue-500/20"
                                : "bg-gray-500/10 text-gray-400 border-gray-500/20"
                        }`}
                      >
                        {user.host ? (
                          <Crown className="w-3 h-3 shrink-0" />
                        ) : user.globalRole === "ADMIN" ? (
                          <Shield className="w-3 h-3 shrink-0" />
                        ) : user.globalRole === "STAFF" ? (
                          <UserCog className="w-3 h-3 shrink-0" />
                        ) : (
                          <User className="w-3 h-3 shrink-0" />
                        )}

                        <span className="mt-px leading-none">
                          {user.host ? "HOST" : user.globalRole.split("_").join(" ")}
                        </span>
                      </span>
                    </td>

                    {/* Status */}
                    <td className="px-6 py-4">
                      <span
                        className={`inline-flex items-center gap-1.5 px-2.5 py-1 rounded-full text-xs font-medium border ${
                          user.status === "ACTIVE"
                            ? "bg-emerald-500/10 text-emerald-400 border-emerald-500/20"
                            : user.status === "ELIMINATED"
                              ? "bg-red-500/10 text-red-400 border-red-500/20"
                              : user.status === "INACTIVE"
                                ? "bg-yellow-500/10 text-yellow-400 border-yellow-500/20"
                                : user.status === "NOT_CONTESTANT"
                                  ? "bg-gray-500/10 text-gray-400 border-gray-500/20"
                                  : user.status === "DID_NOT_SUBMIT"
                                    ? "bg-orange-500/10 text-orange-400 border-orange-500/20"
                                    : "bg-gray-500/10 text-gray-400 border-gray-500/20"
                        }`}
                      >
                        {user.status === "ACTIVE" ? (
                          <CheckCircle2 className="w-3 h-3 shrink-0" />
                        ) : (
                          <XCircle className="w-3 h-3 shrink-0" />
                        )}

                        <span className="mt-px leading-none">
                          {user.status.split("_").join(" ")}
                        </span>
                      </span>
                    </td>

                    {/* Actions */}
                    {isAdmin && (
                      <td className="px-6 py-4 text-right space-x-3">
                        {!user.host || currentUserId === user.discordId ? (
                          <>
                            <button
                              onClick={() => handleOpenEdit(user)}
                              className="text-[#5865F2] hover:text-[#4752C4] font-medium transition-colors inline-flex items-center"
                            >
                              <Edit className="w-4 h-4 mr-1" /> Edit
                            </button>

                            {!user.host && (
                              <button
                                onClick={() => setUserToDelete(user)}
                                className="text-red-400 hover:text-red-500 font-medium transition-colors inline-flex items-center"
                              >
                                <Trash2 className="w-4 h-4 mr-1" /> Delete
                              </button>
                            )}
                          </>
                        ) : (
                          <span className="text-xs font-bold text-[#4E5058] uppercase italic cursor-not-allowed">
                            Protected
                          </span>
                        )}
                      </td>
                    )}
                  </tr>
                ))
              ) : (
                <tr>
                  <td colSpan={isAdmin ? 5 : 4} className="px-6 py-8 text-center text-[#80848E]">
                    No users found matching "{searchTerm}"
                  </td>
                </tr>
              )}
            </tbody>
          </table>
        )}
      </div>

      {/* Multipurpose Modal Overlay (Create / Edit) */}
      {isModalOpen && (
        <div className="fixed inset-0 bg-black/60 backdrop-blur-sm flex items-center justify-center z-50 p-4">
          <div className="bg-[#2B2D31] rounded-xl border border-[#1E1F22] w-full max-w-md shadow-2xl overflow-hidden">
            {/* Modal Header */}
            <div className="flex items-center justify-between p-5 border-b border-[#1E1F22]">
              <h2 className="text-lg font-bold text-white">
                {editingUserId ? "Edit User" : "Add New User"}
              </h2>
              <button
                onClick={() => setIsModalOpen(false)}
                className="text-[#80848E] hover:text-white transition-colors"
              >
                <X className="w-5 h-5" />
              </button>
            </div>

            {/* Modal Form */}
            <form onSubmit={handleSubmit} className="p-5 space-y-4">
              <div>
                <label className="block text-xs font-semibold text-[#80848E] uppercase mb-1.5">
                  Discord ID
                </label>
                <input
                  type="text"
                  required
                  value={formData.discordId}
                  onChange={(e) => setFormData({ ...formData, discordId: e.target.value })}
                  className="w-full bg-[#1E1F22] border border-[#1E1F22] text-[#DBDEE1] rounded-md px-3 py-2 focus:border-[#5865F2] focus:ring-1 focus:ring-[#5865F2] outline-none transition-all"
                  placeholder="e.g. 123456789012345678"
                />
              </div>

              <div>
                <label className="block text-xs font-semibold text-[#80848E] uppercase mb-1.5">
                  Username
                </label>
                <input
                  type="text"
                  required
                  value={formData.username}
                  onChange={(e) => setFormData({ ...formData, username: e.target.value })}
                  className="w-full bg-[#1E1F22] border border-[#1E1F22] text-[#DBDEE1] rounded-md px-3 py-2 focus:border-[#5865F2] focus:ring-1 focus:ring-[#5865F2] outline-none transition-all"
                  placeholder="e.g. MicDropKing"
                />
              </div>

              <div>
                <label className="block text-xs font-semibold text-[#80848E] uppercase mb-1.5">
                  Global Role
                </label>
                <select
                  value={formData.globalRole}
                  onChange={(e) => setFormData({ ...formData, globalRole: e.target.value as any })}
                  className="w-full bg-[#1E1F22] border border-[#1E1F22] text-[#DBDEE1] rounded-md px-3 py-2 focus:border-[#5865F2] focus:ring-1 focus:ring-[#5865F2] outline-none transition-all appearance-none"
                >
                  <option value="USER">USER (Contestant/Judge)</option>
                  <option value="STAFF">STAFF (Organizer)</option>
                  <option value="ADMIN">ADMIN (Full Access)</option>
                </select>
              </div>

              {/* Status field only visible when editing */}
              {editingUserId && (
                <div>
                  <label className="block text-xs font-semibold text-[#80848E] uppercase mb-1.5">
                    Contestant Status
                  </label>
                  <select
                    value={formData.status}
                    onChange={(e) => setFormData({ ...formData, status: e.target.value as any })}
                    className="w-full bg-[#1E1F22] border border-[#1E1F22] text-[#DBDEE1] rounded-md px-3 py-2 focus:border-[#5865F2] focus:ring-1 focus:ring-[#5865F2] outline-none transition-all appearance-none"
                  >
                    <option value="ACTIVE">ACTIVE</option>
                    <option value="INACTIVE">INACTIVE</option>
                    <option value="ELIMINATED">ELIMINATED</option>
                    <option value="NOT_CONTESTANT">NOT_CONTESTANT</option>
                    <option value="DID_NOT_SUBMIT">DID_NOT_SUBMIT</option>
                  </select>
                </div>
              )}

              {/* Modal Footer */}
              <div className="pt-4 flex items-center justify-end gap-3">
                <button
                  type="button"
                  onClick={() => setIsModalOpen(false)}
                  className="px-4 py-2 text-sm font-medium text-[#DBDEE1] hover:underline"
                >
                  Cancel
                </button>
                <button
                  type="submit"
                  disabled={isSubmitting}
                  className="bg-[#5865F2] hover:bg-[#4752C4] text-white px-6 py-2 rounded-md text-sm font-medium transition-all flex items-center gap-2 disabled:opacity-50 disabled:cursor-not-allowed"
                >
                  {isSubmitting ? (
                    <Loader2 className="w-4 h-4 animate-spin mr-2" />
                  ) : (
                    <Save className="w-4 h-4" />
                  )}
                  {isSubmitting ? "Saving..." : editingUserId ? "Update User" : "Save User"}
                </button>
              </div>
            </form>
          </div>
        </div>
      )}

      {/* Delete Confirmation Modal */}
      {userToDelete && (
        <div className="fixed inset-0 bg-black/60 backdrop-blur-sm flex items-center justify-center z-50 p-4">
          <div className="bg-[#2B2D31] rounded-xl border border-[#1E1F22] w-full max-w-sm shadow-2xl overflow-hidden">
            <div className="p-6 text-center">
              <div className="w-16 h-16 rounded-full bg-red-500/10 flex items-center justify-center mx-auto mb-4">
                <AlertTriangle className="w-8 h-8 text-red-500" />
              </div>

              <h2 className="text-xl font-bold text-white mb-2">Delete User</h2>
              <p className="text-[#80848E] text-sm">
                Are you sure you want to delete{" "}
                <span className="font-bold text-[#DBDEE1]">{userToDelete.username}</span>? This
                action cannot be undone.
              </p>
            </div>

            {/* Action Buttons */}
            <div className="bg-[#1E1F22] p-4 flex items-center justify-end gap-3">
              <button
                type="button"
                onClick={() => setUserToDelete(null)}
                disabled={isSubmitting}
                className="px-4 py-2 text-sm font-medium text-[#DBDEE1] hover:underline disabled:opacity-50 disabled:cursor-not-allowed"
              >
                Cancel
              </button>
              <button
                type="button"
                onClick={handleDeleteConfirm}
                disabled={isSubmitting}
                className="bg-red-500 hover:bg-red-600 text-white px-6 py-2 rounded-md text-sm font-medium transition-all flex items-center gap-2 disabled:opacity-50 disabled:cursor-not-allowed"
              >
                {isSubmitting ? (
                  <Loader2 className="w-4 h-4 animate-spin mr-2" />
                ) : (
                  <Trash2 className="w-4 h-4" />
                )}
                {isSubmitting ? "Deleting..." : "Delete"}
              </button>
            </div>
          </div>
        </div>
      )}
    </div>
  );
}
